### PR TITLE
add injection for css and js files

### PR DESCRIPTION
**Pull request by rphuber**
add injection for bower, css and app js files in gulpfile

### CODE REVIEW

**Comment by rphuber** [comment]
I also removed the tab validation from the jscs (I use 2 space tabs and most everyone else is probably using 4 space tabs) so as to not throw warnings in gulp task

**Comment by rphuber** [comment]
Added in browser sync and file watching.  Having trouble getting it to auto open but once I refresh it works fine.

**Comment by rphuber** [comment]
added comments to the readme about running locally

**Comment by calweb** [comment]
nice work, yet again!  browsersync is really awesome, btw - really great for onsite user testingand demoing on multi devices

**Comment by rphuber** [comment]
Thanks.  I am going to work on a build task next.  Anything else you think we should add?

**Pull request merged**
